version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "monthly" # to reduce frequency of npm updates

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
