name: Setup
description: Setup working directory to perform Gradle or NPM tasks

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: ui/package-lock.json

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5