version: 0.2

phases:
  build:
    commands:
      - ./gradlew gatlingRun -x build --info --build-cache --no-daemon

artifacts:
  files:
    - results/*

cache:
  paths:
    - /root/.gradle/caches/**/*
    - /root/.gradle/nodejs/**/*
    - /root/.gradle/npm/**/*
    - /root/.npm/**/*
    - ./**/.local-chromium/**/*