spring:
  datasource:
    url: 'jdbc:oracle:thin:@localhost:1521:XE'
    username: example
    password: example
  jpa:
    hibernate.ddl-auto: none
  ldap:
    base: dc=moj,dc=com
    urls: ldap://localhost:389
    username: cn=example,dc=moj,dc=com
    password: example
    useOracleAttributes: false
  data.redis:
    host: localhost
    port: 6379

delius:
  ldap.base:
    users: ou=Users
    groups: ou=Groups
    clients: ou=Clients
    roles: ou=Roles
    role-groups: ou=RoleGroups
