spring.application.name: ndelius-um

spring.resources.static-locations: classpath:/ui

jwt:
  cookie: AUTH-TOKEN
  expiry: 30
  secret: a-randomly-generated-secret-key # change me!

spring.jpa.properties.hibernate.search.default:
  directory_provider: filesystem
  indexBase: ./um-index/
  expiry: 600 # 10 minutes

logging.level:
  org.springframework.web: ERROR
  org.hibernate.search.batchindexing: WARN
