spring.application.name: ndelius-um

server:
  servlet.context-path: /umt
  compression:
    enabled: true # Enable GZIP compression
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring.resources:
  static-locations: classpath:/ui
  cache.cachecontrol:
    cache-public: true # Enable resource caching by browser or intermediaries
    no-cache: true     # Enable revalidation on each request

cache.evict.delay: 86400000 # = 24*60*60*1000 = 24 hours

spring.main.allow-bean-definition-overriding: true  # This allows us to override the embedded LDAP with our alias-dereferencing version

spring.ldap.base-environment:
  java.naming.ldap.derefAliases: never
  com.sun.jndi.ldap.connect.pool: true

spring.session.store-type: redis
spring.data.redis.repositories.enabled: false

management.endpoints.web.exposure.include: ["health", "info", "metrics"]
management.endpoint.health.show-details: always

logging.level:
  org.springframework.web: ERROR

logging.file.path: ./log/