spring.application.name: ndelius-um

spring.profiles.group:
  dev: default
  test: dev

server:
  servlet.context-path: /umt
  compression.enabled: true # Enable GZIP compression

spring.web.resources:
  chain.strategy.content.enabled: true
  cache.cachecontrol:
    cache-public: true # Enable resource caching by browser or intermediaries
    no-cache: true     # Enable revalidation on each request

cache.evict.delay: 86400000 # = 24*60*60*1000 = 24 hours

spring.ldap.base-environment:
  java.naming.ldap.derefAliases: never
  com.sun.jndi.ldap.connect.pool: true

spring.session.store-type: redis
spring.data.redis.repositories.enabled: false

management.endpoints.web.exposure.include: ["health", "info", "metrics"]
management.endpoint.health.show-details: always

info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}

logging.level:
  org.springframework.web: ERROR

logging.file.path: ./log/