spring.application.name: ndelius-um

server.servlet.context-path: /umt
spring.resources.static-locations: classpath:/ui

cache.evict.delay: 86400000 # = 24*60*60*1000 = 24 hours

spring.main.allow-bean-definition-overriding: true  # This allows us to override the embedded LDAP with our alias-dereferencing version

spring.ldap.base-environment:
  java.naming.ldap.derefAliases: never
  com.sun.jndi.ldap.connect.pool: true

management.endpoints.web.exposure.include: ["health", "info", "metrics"]
management.endpoint.health.show-details: always

logging.level:
  org.springframework.web: ERROR

logging.path: ./log/