spring.application.name: ndelius-um

spring.resources.static-locations: classpath:/ui

jwt:
  cookie: AUTH-TOKEN
  expiry: 30

spring.jpa.properties.hibernate.search.default:
  directory_provider: filesystem
  indexBase: ./um-index/
  expiry: 600 # 10 minutes

oid.default-password: '{SSHA}S22CgeZ/VQJHivxBKe0kONRCA1XelJr0'
oid.base-environment.java.naming.ldap.derefAliases: never
oid.base-environment.com.sun.jndi.ldap.connect.pool: false

management.endpoint.health.show-details: always

logging.level:
  org.springframework.web: ERROR
  org.hibernate.search.batchindexing: WARN

logging.path: ./log/