spring:
  datasource:
    url: 'jdbc:oracle:thin:@localhost:1521:XE'
    type: oracle.jdbc.pool.OracleDataSource
    username: example
    password: example
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate.ddl-auto: none
  ldap:
    base: ou=Users,dc=moj,dc=com
    urls: ldap://localhost:389
    username: cn=example,dc=moj,dc=com
    password: example
    useOracleAttributes: false
  redis:
    host: localhost
    port: 6379
