spring.application.name: ndelius-um

server.servlet.context-path: /umt
spring.resources.static-locations: classpath:/ui

jwt:
  cookie: AUTH-TOKEN
  expiry: 30

oid.default-password: '{SSHA}S22CgeZ/VQJHivxBKe0kONRCA1XelJr0'
oid.base-environment:
  java.naming.ldap.derefAliases: never
  com.sun.jndi.ldap.connect.pool: true

management.endpoints.web.exposure.include: ["health", "info", "metrics"]
management.endpoint.health.show-details: always

logging.level:
  org.springframework.web: ERROR

logging.path: ./log/