# Generic task-definition template
cpu: "{{ .values.resources.cpu }}"
memory: "{{ .values.resources.memory }}"
containerDefinitions:
  - image: "{{ .values.image.name }}:{{ .Env.VERSION }}"
    healthCheck:
      command: ["CMD-SHELL", "{{ .values.healthcheck.command }}"]
    cpu: {{ .values.resources.cpu }}
    memory: {{ .values.resources.memory }}
    environment:
    {{- range $key, $val := .values.env }}
    - name: {{ $key }}
      value: "{{ $val }}"
    {{- end }}
    secrets:
    {{- range $key, $val := .values.secrets }}
    - name: {{ $key }}
      valueFrom: "{{ $val }}"
    {{- end }}