---
generic-service:
  ingress:
    host: delius-user-management-stage.hmpps.service.justice.gov.uk

  env:
    DELIUS_PASSWORD-RESET_URL: https://password-reset.stage.probation.service.justice.gov.uk/public/forgottenpassword

  scheduledDowntime:
    enabled: true

  allowlist:
    mod-platform-live-eu-west-2a-nat: "13.41.38.176/32"
    mod-platform-live-eu-west-2c-nat: "3.11.197.133/32"
    mod-platform-live-eu-west-2b-nat: "3.8.81.175/32"
  
