---
generic-service:
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi

  ingress:
    host: delius-user-management-preprod.hmpps.service.justice.gov.uk

  env:
    DELIUS_PASSWORD-RESET_URL: https://password-reset.pre-prod.delius.probation.hmpps.dsd.io/public/forgottenpassword
