---
generic-service:
  ingress:
    host: delius-user-management-test.hmpps.service.justice.gov.uk

  env:
    LOGGING_LEVEL_UK_CO_BCONLINE_NDELIUS: DEBUG
    DELIUS_PASSWORD-RESET_URL: https://password-reset.test.probation.service.justice.gov.uk/public/forgottenpassword

  scheduledDowntime:
    enabled: true

  allowlist:
    mod-platform-non-live-eu-west-2b-nat: "13.42.163.245/32"
    mod-platform-non-live-eu-west-2a-nat: "13.43.9.198/32"
    mod-platform-non-live-eu-west-2c-nat: "18.132.208.127/32"