name: Accessibility

on:
  push:
    paths:
      - ui/**
      - .github/workflows/accessibility.yml

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - name: Run accessibility checks
        run: |
          ./gradlew assemble
          SPRING_PROFILES_ACTIVE=dev ./gradlew bootRun &
          npm run accessibility --prefix=ui
          ./gradlew --stop

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: accessibility-report
          path: ui/pa11y-ci-report