name: Accessibility

on: push

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run accessibility checks
        run: |
          ./gradlew assemble --build-cache
          SPRING_PROFILES_ACTIVE=dev ./gradlew bootRun --build-cache &
          npm run accessibility --prefix=ui
          ./gradlew --stop

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: accessibility-report
          path: ui/dist/reports/pa11y