name: Code Quality

on:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  analyze-java:
    name: Analyze Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: github/codeql-action/init@v3
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  lint-typescript:
    name: Lint Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Lint
        run: ./gradlew npm_run_lint