name: Check dependencies

on: push

jobs:
  gradle-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run tests
        run: ./gradlew dependencyCheckAnalyze --build-cache