name: Security

on: push

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Analyze Gradle dependencies
        run: ./gradlew dependencyCheckAnalyze --build-cache

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: vulnerability-report
          path: build/reports/dependency-check-report.html