name: Security

on:
  push:
    paths:
      - build.gradle
      - dependency-check-suppression.xml

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Analyze Gradle dependencies
        run: ./gradlew dependencyCheckAnalyze

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: vulnerability-report
          path: build/reports/dependency-check-report.html